### ISSUE TITLE
Missing midi data

### ISSUE THREAD

**Issue by connortreacy** [montoyamoraga/drum-machine-patterns#4]
This project is really exciting! I have this exact book, and wanted to transcribe the patterns for use in Ableton. 
I see you've created markdown tables but I don't see any midi data in the repo. Is this work in progress? Is there something I can do to help?

**Comment by montoyamoraga** [comment]
hey i haven't done them, and no plans on working on it this year, if you wanna send them over a PR, happy to add it!
